### ISSUE TITLE
Problemas con empaquetamiento en Fedora

### ISSUE THREAD

**Issue by Richzendy** [satanas/Turpial#12]
Estoy actualmente llevando el paquete turpial de manera oficial a los repositorios de Fedora, entre las evaluaciones del paquete hay un par de sugerencias que tienen que ver directamente con el código fuente, una es la ubicación de los archivos de lenguajes.

"1.The biggest problem for this package is the location for locale. The right place for them should be /usr/share/locale/, the upstream must fix them. I suggest you send a patch to upstream,
/usr/lib/python2.6/site-packages/turpial/i18n is not the appropriate place for them."

Textualmente de la persona que a ido revisando mi paquete, quiere decir que el estándar indica que los archivos de locales, deben ir en /usr/share/locale y a tal efecto se debe cambiar también el nombre de los archivos desde messages.\* a turpial.\* 

Y la otra tiene que ver con el archivo .desktop, en el se da el path relativo del archivo de icono, debería colocarse le path absoluto y además sería recomendable por ejemplo incluso cambiarlo de nombre a simplemente turpial.png.

Ver referencia de este bug en:

https://bugzilla.redhat.com/show_bug.cgi?id=592733

**Comment by satanas** [comment]
Is this issue still valid with Turpial 3?

**Comment by Richzendy** [comment]
No, i will close this issue, this issue was opened 4 years ago.
