### ISSUE TITLE
Enlace a perfil de usuario en identi.ca

### ISSUE THREAD

**Issue by davidhdz** [satanas/Turpial#14]
En Identi.ca, al abrir el menú despegable con el botón derecho del ratón → Open → nombre_usuario 
nos abre una página del navegador al perfil de twitter (si lo tiene) y no enlaza al perfil de Identi.ca como debería ser.

Lo mismo sucede con Menú despegable → nombre_usuario.

**Comment by satanas** [comment]
Corregido. Disponible en la rama newface que será integrada próximamente a development
