### ISSUE TITLE
Cuelge al iniciar, debug no da suficiente informacion

### ISSUE THREAD

**Issue by pedro-am** [satanas/Turpial#17]
Estoy usando la version en el ppa
http://ppa.launchpad.net/effie-jayx/turpial/ubuntu/ lucid/main turpial 1.3.3-0ubuntu3~lucid 
Ubuntu 64 bits
Linux alexia 2.6.32-23-generic #37-Ubuntu SMP Fri Jun 11 08:03:28 UTC 2010 x86_64 GNU/Linux

$ turpial -d
DEBUG:Sound:Iniciado
DEBUG:Gtk:Cargado modo GTK Simple
DEBUG:Services:Iniciado
DEBUG:API:Iniciado
DEBUG:Controller:Iniciando Turpial
DEBUG:API:Iniciando autenticacion basica
DEBUG:Config:Cargando archivo
DEBUG:Config:Leyendo sección Auth
DEBUG:API:Iniciando OAuth
DEBUG:Gtk:Cargando ventana principal
DEBUG:Gtk:Actualizando configuracion
DEBUG:Config:Leyendo sección Notifications
DEBUG:Gtk:Cambiando a modo single ((517, 737))
DEBUG:Gtk:--Creado timer de Timeline cada 3 min
DEBUG:Gtk:--Creado timer de Replies cada 5 min
DEBUG:Gtk:--Creado timer de Directs cada 7 min

y se queda ahi

No se refresca la ventana si pongo otra ventana encima, tampoco responde el icono en la barra

Pense que podria ser algun problema con los datos de la version anterior asi que elimine la carpeta .config/turpial

Al iniciar me pide el token y se cuelga de nuevo

$ turpial -d
DEBUG:Sound:Iniciado
DEBUG:Gtk:Cargado modo GTK Simple
DEBUG:Services:Iniciado
DEBUG:API:Iniciado
DEBUG:Controller:Iniciando Turpial
DEBUG:API:Iniciando autenticacion basica
DEBUG:Config:Creando archivo
DEBUG:Config:Cargando archivo
DEBUG:Config:Leyendo sección Auth
DEBUG:API:Iniciando OAuth
DEBUG:API:Obtain a request token
DEBUG:API:REQUEST (via headers)
DEBUG:API:parameters: {'oauth_nonce': '39934612', 'oauth_timestamp': 1278878625, 'oauth_consumer_key': '-editado-', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_version': '1.0', 'oauth_signature': '-editado-'}
DEBUG:API:GOT
DEBUG:API:key: -editado-
DEBUG:API:secret: -editado-
DEBUG:API:callback confirmed? true
DEBUG:API:Authorize the request token
DEBUG:API:REQUEST (via url query string)
DEBUG:API:parameters: {'oauth_token': -editado- } 
DEBUG:API:Solicitando autenticacion del token

**Comment by satanas** [comment]
Hola Pedro,

¿Qué versión estás usando? Al parecer es la 1.0 y esa dejó de funcionar con los cambios que hizo Twitter en la autenticación. Puedes encontrar más información en http://turpial.org.ve. Te recomiendo que actualices a la versión 1.3.4 e intentes de nuevo.

Saludos

**Comment by pedro-am** [comment]
No, no es la version 1.0,  1.3.3-0ubuntu3~lucid 
Este reporte era de antes de que deshabilitaran la autenticacion basica.

Ya funciona con la 1.3.4-0ubuntu1~lucid

Gracias

**Comment by satanas** [comment]
Perfecto. Cerraré el ticket entonces.

Saludos y gracias por la información
