### ISSUE TITLE
Agregar numero de version en modo debug 

### ISSUE THREAD

**Issue by pedro-am** [satanas/Turpial#19]
pedro@alexia:~$ turpial -d 
**DEBUG: Version 1.3.4**
DEBUG:Sound:Iniciado
DEBUG:Gtk:Cargado modo GTK Simple

Creo que seria mas facil saber si esta ejecutando la ultima version o esta ejecutando una desde egg

**Comment by satanas** [comment]
Listo, esa funcionalidad ha sido implementada hace unos días.

Gracias por la sugerencia
