### ISSUE TITLE
Turpial shouldn't break if there is no internet before opening

### ISSUE THREAD

**Issue by satanas** [satanas/Turpial#204]

**Comment by sebasmagri** [comment]
I believe this could be handled by libturpial, probably in the accountmanager level. We could have a way to track the status of an account (disconnected, authed, etc) and show information in the UI properly according to this.

**Comment by satanas** [comment]
Yep, totally agree but I don't have in mind to release another libturpial version until the release of Turpial 3, so what I'm doing is to "hack" this things on Turpial code, label them with a comment like below and registering the issue in libturpial's repo:

``` python
#FIXME: This should be implemented on libturpial
```

or

``` python
#HACK: Implement this on libturpial
```

What do you think?

**Comment by sebasmagri** [comment]
I guess it's because you want to work on Turpial only. However there we should keep this in mind as this will ease everything.

**Comment by satanas** [comment]
Yep, of course. After Turpial 3 release (while the people is still enjoy the new version) I will be working on a new release of libturpial with all this fixes and this will drive us directly into a new turpial release too (somekind of maintenance release). That's the plan

**Comment by satanas** [comment]
Done
