### ISSUE TITLE
Orden de actualizaciones poco conveniente

### ISSUE THREAD

**Issue by pointtonull** [satanas/Turpial#21]
El actual ordenamiento resulta muy poco intuitivo y dificulta la lectura fluida; por eso creo que debería existir la opción para que las actualizaciones sean mostradas en el orden cronológico natural (i.e.: NO-inverso).

e.g.: Una conversación se ve así con el actual ordenamiento:
- @tu Porque así se facilita el seguimiento del tema tratado.
- @yo ¿Por qué?
- @tu Es preferible escribir debajo del párrafo al que se responde.
- @yo ¿Entonces qué se hace?
- @tu No.
- @yo ¿Es bueno hacer "top-posting"?

Y podría verse así cuando el usuario active la opción:
- @yo ¿Es bueno hacer "top-posting"?
- @tu No.
- @yo ¿Entonces qué se hace?
- @tu Es preferible escribir debajo del párrafo al que se responde.
- @yo ¿Por qué?
- @tu Porque así se facilita el seguimiento del tema tratado.

Adicionalmente habría que modificar el comportamiento de  "Autoscrolling" para que, cuando esta opción esté activada, mantenga visible el último en lugar del primer elemento de la lista.

**Comment by satanas** [comment]
This issue depends a lot in how Twitter handles and send information. We can't modify the way it should be (according to Twitter policies). Won't fix
