### ISSUE TITLE
Error compilación en archlinux

### ISSUE THREAD

**Issue by abr4xas** [satanas/Turpial#214]
Hola,
Estaba tratando de crear el pkgbuild para archlinux y me salio el siguiente error: 

``` shell
==> Iniciando prepare()...
patching file turpial/main.py
Hunk #1 FAILED at 18.
1 out of 1 hunk FAILED -- saving rejects to file turpial/main.py.rej
==> ERROR: Se produjo un error en prepare().
    Cancelando...
```

En aur se encuentra: turpial-git https://aur.archlinux.org/packages/turpial-git/ marcado como desactualizado por lo cual decidi crear un paquete nuevo: turpial-dev https://aur.archlinux.org/packages/turpial-dev/ en este caso, elimine la siguientes lineas:

``` shell
prepare() {
    cd $pkgname/
    patch -p1 -i ../config.patch
}
```

de mi pkgbuild, lo instala pero no logra iniciar.

**Comment by abr4xas** [comment]
Bueno, he estado investigando y el problema es el config.patch que contiene:

``` python
--- a/turpial/main.py
+++ b/turpial/main.py
@@ -18,7 +18,7 @@ from turpial.ui import util

 from libturpial.api.core import Core
 from libturpial.common.tools import *
-from libturpial.lib.config import AppConfig
+from libturpial.config import AppConfig
 from libturpial import VERSION as LIBTURPIAL_VERSION

 LOG_FMT = logging.Formatter('[%(asctime)s] [%(name)s::%(levelname)s] %(message)s', '%Y%m%d-%H:%M')

```

Entonces, no se como solventar ese error, si me ayudan puedo tener listo el paquete lo más pronto posible.

Gracias :+1:  :D

**Comment by satanas** [comment]
Hola Angel, ¿Puedes correr Turpial en una consola y enviarme la salida que genera? Dale un vistazo a la documentación de instalación a ver si te ayuda en algo http://wiki.turpial.org.ve/dev:installation

Saludos y gracias por el interés :)

**Comment by abr4xas** [comment]
Epale, esto es lo que me sale

``` python
[abr4xas@Genius libturpial]$ sudo python setup.py develop
[sudo] password for abr4xas: 
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from ez_setup import use_setuptools
  File "/home/abr4xas/git/libturpial/ez_setup.py", line 106
    except pkg_resources.VersionConflict, e:
                                        ^
SyntaxError: invalid syntax

```

**Comment by satanas** [comment]
Necesitas tener instalado setuptools. Acabo de agregarlo a la lista de dependencias en http://wiki.turpial.org.ve/dev:dependencies ;)

**Comment by abr4xas** [comment]
Si lo tengo instalado, fijate

``` shell
[abr4xas@Genius libturpial]$ yaourt -Ss python2-distribute 
extra/python2-setuptools 1.3-1 [installed]
    Easily download, build, install, upgrade, and uninstall Python packages
aur/libx32-python2-distribute 0.6.30-1.1 (Out of Date) (0)
    Easily build and distribute Python packages (x32 ABI)
```

Aunque libx32-python2-distribute diga Out of Date lo acabo de reinstalar, hay que esperar que el mantenedor del paquete le haga la actualización y luego probar si corre bien. :)

**Comment by satanas** [comment]
Pero es raro porque yo tengo Arch y todo el desarrollo lo he hecho sobre
Arch y no me ha dado ese problema. Intenta desinstalar python2-distribute e
instala python2-setuptools a ver (y no uses aur, tratemos de que sean las
versiones oficiales).

Saludos

2013/11/19 ángel notifications@github.com

> Si lo tengo instalado, fijate
> 
> [abr4xas@Genius libturpial]$ yaourt -Ss python2-distribute
> extra/python2-setuptools 1.3-1 [installed]
>     Easily download, build, install, upgrade, and uninstall Python packages
> aur/libx32-python2-distribute 0.6.30-1.1 (Out of Date) (0)
>     Easily build and distribute Python packages (x32 ABI)
> 
> Aunque libx32-python2-distribute diga Out of Date lo acabo de reinstalar,
> hay que esperar que el mantenedor del paquete le haga la actualización y
> luego probar si corre bien. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/satanas/Turpial/issues/214#issuecomment-28778688
> .

## 

“Yo construyo Soberanía, uso Software Libre”
Wil A. Alvarez
Linux Counter #415026
Debian Counter #259
http://turpial.org.ve
http://damncorner.blogspot.com/

**Comment by abr4xas** [comment]
Epale, viejo re-instale las dependencias usando pacman como indicaste y nada =S de verdad que no entiendo que pasa, no creo que sea mi instalación porque tiengo una semana que re-instale en la portatil. La verdad no se que pueda pasar. :(

**Comment by satanas** [comment]
Estás usando Python 2 ¿verdad? :P

El 20 de noviembre de 2013 20:13, ángelnotifications@github.com escribió:

> Epale, viejo re-instale las dependencias usando pacman como indicaste y
> nada =S de verdad que no entiendo que pasa, no creo que sea mi instalación
> porque tiengo una semana que re-instale en la portatil. La verdad no se que
> pueda pasar. :(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/satanas/Turpial/issues/214#issuecomment-28941691
> .

## 

“Yo construyo Soberanía, uso Software Libre”
Wil A. Alvarez
Linux Counter #415026
Debian Counter #259
http://turpial.org.ve
http://damncorner.blogspot.com/

**Comment by abr4xas** [comment]
Hola,
Efectivamente el problema era que no estaba usando python2 xD... Pero listo, ya pude correrlo sin problema.
De igual manera, voy a esperar a que saques una estable para no mandar esta al repo de aur.

Cerrado.

**Comment by satanas** [comment]
Excelente :+1:
