### ISSUE TITLE
Diacritic dont show on tweet with keyboard layout configuration 'latam' or 'es'

### ISSUE THREAD

**Issue by angelbladex** [satanas/Turpial#236]
When write a tweet  and it's required a diacritc (á é í...) ,show it wrong

sample
you type "acción"  you get accio'n"

Turpial 3.0-b1

**Comment by satanas** [comment]
This is a known bug but don't know how to fix it yet

**Comment by satanas** [comment]
This issue addresses the problem registered as #161 so will be closed and marked as duplicated in favor of the older

**Comment by satanas** [comment]
Hey @angelbladex, have you experienced this issue in the current development version?

**Comment by angelbladex** [comment]
Sorry, i don't use Turpial. i can do a fresh test but i dont have time for now. :(

**Comment by angelbladex** [comment]
Turpial 3.5.9-dev run nice on my laptop with ArchLinux

**Comment by satanas** [comment]
Great! thanks
