### ISSUE TITLE
turpial 3.0-b1 not update tweets if you don't have notification daemon running

### ISSUE THREAD

**Issue by Richzendy** [satanas/Turpial#237]
I was testing turpial on Fedora19 with LXDE desktop enviroment and them turpial don't update timeline if you don't have notification daemon running, i see this error in debug mode:

GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

i start my notification daemon with:

/usr/libexec/notification-daemon  start &

And them turpial it's working now, i think could be better if turpial show a window whit this error or sugerences to people whitout gnome or kde.

**Comment by satanas** [comment]
Thanks for the bug report. I'm going to check the issue before the final release

**Comment by satanas** [comment]
@Richzendy Could you send me the complete output for this bug? That way I don't need to uninstall my notifications daemon to reproduce it

**Comment by Richzendy** [comment]
This is the only error in to logs: 

GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

**Comment by satanas** [comment]
@Richzendy Is there no more information? A more verbose debug output would be really helpful to try to figure out where is the error happening (file, number of line, etc). Otherwise I couldn't do too much

**Comment by Richzendy** [comment]
turpial (beta2) now refresh the timeline whitout notification daemon, this is a full debug log:

[Richzendy@olivaw SPECS]$ turpial -d
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/**init**.py:122: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
loaded the Generic plugin 
DEBUG:AppConfig:Started
DEBUG:AppConfig:CONFIG_FILE: /home/Richzendy/.config/turpial/config
DEBUG:AppConfig:FILTERS_FILE: /home/Richzendy/.config/turpial/filtered
DEBUG:AppConfig:FRIENDS_FILE: /home/Richzendy/.config/turpial/friends
DEBUG:AppConfig:Loaded configuration
DEBUG:change me:Started
DEBUG:AccountConfig:CACHEDIR: /home/Richzendy/.cache/turpial/Richzendy-twitter/images
DEBUG:AccountConfig:CONFIGFILE: /home/Richzendy/.config/turpial/accounts/Richzendy-twitter/config
DEBUG:AccountConfig:Loaded configuration
DEBUG:Controller:Starting Turpial 3.0-b2
DEBUG:TurpialHTTP:Validated SSL cert for host: api.twitter.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/account/verify_credentials.json HTTP/1.1" 200 977
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/lists/list.json?screen_name=Richzendy HTTP/1.1" 200 881
--Created timer for Richzendy-twitter-timeline every 300000 sec
--Created timer for Richzendy-twitter-replies every 300000 sec
--Created timer for Richzendy-twitter-directs every 300000 sec
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/home_timeline.json?count=60&include_entities=True HTTP/1.1" 200 25156
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/mentions_timeline.json?count=60&include_entities=True HTTP/1.1" 200 17869
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/direct_messages.json?count=60&include_entities=True HTTP/1.1" 200 12288
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
DEBUG:urllib3.connectionpool:"GET /1.1/friends/ids.json?cursor=-1 HTTP/1.1" 200 3745
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=1412749064%2C2188640280%2C34196832%2C191158687%2C1465991160%2C504737648%2C86368811%2C204072441%2C92173536%2C432751812%2C18344450%2C100731315%2C187085548%2C18996060%2C96799379%2C555928038%2C1546823898%2C559882002%2C142075658%2C199569043%2C83471831%2C32139177%2C1059506833%2C221617799%2C166255930%2C20777992%2C101329724%2C493171168%2C46670078%2C326162536%2C147274572%2C324511975%2C1225314666%2C1276625588%2C63263205%2C79327561%2C14136690%2C85976325%2C458025085%2C14424151%2C133086921%2C63585592%2C305957356%2C73322452%2C551208828%2C13334762%2C14132674%2C32499999%2C199760435%2C977065164%2C40112868%2C232730257%2C39184406%2C21975149%2C1857421%2C53932701%2C57440969%2C23313894%2C14266199%2C25903489%2C1077310099%2C18780270%2C86786657%2C16690810%2C172210678%2C42317616%2C972651%2C92615439%2C240455281%2C1105348578%2C189178882%2C861275917%2C140620659%2C21767412%2C12470382%2C184619338%2C201789953%2C16254468%2C34507577%2C186108816%2C333668789%2C280507552%2C596963130%2C448118032%2C39774237%2C24390692%2C867903643%2C48001264%2C109296506%2C14916839%2C86556093%2C42719222%2C103862663%2C103690811%2C11858232%2C17456270%2C435119060%2C90572703%2C163353201%2C602151203 HTTP/1.1" 200 44956
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=565754571%2C80440340%2C14375294%2C26981455%2C82269962%2C344253343%2C95060522%2C738796448%2C326658079%2C144988772%2C190681215%2C213630712%2C314489263%2C71544889%2C701308015%2C3389221%2C117843976%2C20718994%2C3906191%2C434597929%2C486013940%2C38801267%2C409181411%2C729364148%2C217721601%2C64729645%2C587771871%2C14949454%2C16960753%2C115969204%2C239531667%2C109943488%2C134530196%2C142359326%2C41137418%2C41746908%2C75173200%2C129010299%2C111677646%2C63484454%2C6035252%2C44966220%2C81032548%2C13231902%2C15473958%2C494883886%2C389661845%2C37745226%2C142042291%2C27992505%2C395375443%2C109442071%2C3756831%2C100562129%2C72625007%2C501300140%2C3473621%2C146255863%2C87010330%2C115549104%2C98459553%2C141412729%2C99349204%2C99926444%2C124615143%2C48434822%2C138892116%2C112278793%2C110764615%2C105901957%2C132167584%2C110518778%2C57785152%2C41057207%2C55141937%2C51759473%2C48918861%2C79290691%2C47106499%2C54574413%2C16351784%2C9929622%2C6351662%2C284069689%2C64886054%2C101949871%2C258400748%2C107866555%2C133577765%2C34259816%2C41617215%2C471089948%2C19400946%2C376009267%2C17501369%2C128309221%2C48850329%2C140518868%2C611986351%2C139202123 HTTP/1.1" 200 44773
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=146645130%2C123966801%2C14666205%2C57240601%2C114963606%2C171280977%2C255170447%2C544991457%2C14749606%2C191456848%2C469967838%2C317647291%2C154604973%2C297057211%2C75935380%2C127725981%2C28137831%2C278497176%2C18036676%2C82980990%2C195187948%2C151150589%2C168786120%2C33905807%2C190361879%2C94371793%2C77687778%2C64734835%2C254842187%2C75202953%2C137575942%2C16634447%2C98940507%2C802225%2C19239012%2C106281683%2C6234112%2C37409779%2C14948297%2C81010295%2C75298997%2C109153351%2C403708031%2C352708517%2C82820185%2C512451359%2C233724009%2C113211856%2C141826985%2C24475055%2C86070281%2C50396648%2C91333167%2C364326108%2C108378201%2C15051237%2C133069590%2C223663165%2C356565711%2C21036948%2C352591588%2C145292729%2C16843780%2C302666251%2C305708406%2C28733664%2C286802800%2C8187772%2C166326763%2C132021364%2C247360761%2C87294312%2C2142731%2C107937354%2C344807685%2C354847710%2C125112029%2C69778345%2C112256767%2C43270079%2C74924780%2C147337190%2C429982903%2C18847100%2C438372590%2C287239681%2C280625032%2C25944230%2C134580098%2C137369649%2C133937393%2C14475836%2C8859592%2C109973880%2C19781777%2C312557169%2C313213055%2C105172811%2C4631911%2C387835054 HTTP/1.1" 200 46913
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=42289753%2C216803497%2C120909767%2C109490409%2C33656504%2C362129835%2C95503190%2C20498634%2C92412832%2C172326616%2C14936115%2C169740097%2C118566907%2C167234557%2C53175280%2C343476787%2C113555653%2C137520613%2C107280460%2C43184852%2C201718078%2C227900705%2C106857212%2C92623648%2C377553478%2C15819114%2C17615818%2C30036321%2C100668146%2C317118851%2C46428661%2C21510859%2C171790657%2C152103597%2C96858210%2C272276748%2C87347666%2C140954884%2C49743410%2C157576728%2C109151290%2C144127970%2C6726812%2C75040988%2C52525000%2C81876543%2C17508703%2C71701378%2C52418179%2C103936036%2C93557595%2C40049363%2C15155074%2C134252342%2C43966234%2C92352578%2C14083717%2C349076987%2C189212327%2C199326456%2C143445588%2C19594084%2C130224931%2C197100056%2C40801385%2C11911482%2C12652322%2C331680822%2C149934894%2C134521516%2C329573882%2C119404822%2C66747949%2C258005752%2C166425171%2C246406125%2C45792999%2C50880662%2C97874696%2C328862475%2C69971360%2C84883286%2C64444374%2C60382263%2C138879861%2C113400425%2C234077217%2C97036822%2C17228304%2C50770963%2C66616335%2C77937874%2C319437179%2C150621067%2C52706187%2C214745281%2C142085524%2C226769946%2C269068169%2C137107693 HTTP/1.1" 200 43940
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=89583501%2C209394202%2C19072360%2C314137206%2C5766592%2C264381957%2C12101432%2C90393610%2C248112009%2C51860842%2C16627617%2C237635943%2C10496822%2C305631241%2C13231382%2C126117031%2C136515437%2C141433743%2C216878982%2C254632929%2C190697853%2C136661793%2C49848433%2C95736901%2C165898835%2C97067702%2C16617691%2C17013058%2C294475107%2C52433558%2C68703337%2C202279491%2C115555681%2C85408645%2C146713993%2C12841212%2C262599386%2C279191509%2C197122574%2C278559186%2C63239078%2C134569854%2C153128720%2C273050108%2C271032076%2C143979606%2C147584062%2C23418362%2C137002089%2C39292581%2C18960133%2C26264191%2C77926072%2C259517216%2C83204594%2C232626428%2C16707257%2C220299921%2C18004094%2C2764671%2C43564298%2C213423255%2C52129275%2C192264798%2C93984855%2C108734782%2C102804859%2C200936973%2C16242076%2C233820603%2C218019997%2C168357090%2C143573660%2C113443277%2C85147950%2C65366725%2C227974149%2C122668309%2C16045370%2C177926099%2C9882482%2C135025066%2C201585441%2C92637150%2C148553075%2C176693595%2C215282594%2C17790274%2C211188020%2C39190538%2C133841947%2C62837451%2C190263396%2C25413219%2C7001322%2C17337554%2C35649630%2C146193928%2C8411122%2C59424092 HTTP/1.1" 200 41800
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=14141651%2C116000289%2C128361959%2C194202831%2C812868%2C85426644%2C134664821%2C157115760%2C78366880%2C139594044%2C195558054%2C85361349%2C108338250%2C14877781%2C14204109%2C73809715%2C125146065%2C18525312%2C90448718%2C89717019%2C72751020%2C15072316%2C13959882%2C11945072%2C53458268%2C11545%2C14215272%2C138043198%2C114490934%2C93617072%2C83977792%2C6912112%2C20569760%2C72580043%2C803808%2C53294902%2C66763332%2C106124703%2C48780993%2C98679403%2C112036196%2C101787048%2C54973589%2C71040368%2C55981836%2C134811903%2C65297502%2C149142188%2C35950442%2C109290243%2C54535649%2C17435044%2C76103661%2C11287692%2C147279218%2C165751353%2C108518199%2C91120943%2C82288053%2C76657294%2C66029909%2C62203393%2C58809331%2C55880477%2C54713295%2C47559430%2C40284770%2C26767736%2C18973753%2C18948653%2C17633909%2C16362921%2C15918218%2C14966270%2C14888223%2C14744978%2C14602223%2C14429811%2C14134831%2C9383442%2C6003702%2C777466%2C102763917%2C94524695%2C34970551%2C138250994%2C46858161%2C15666038%2C148751006%2C104975604%2C85091976%2C99199905%2C50871388%2C90944663%2C34499885%2C40915061%2C6508842%2C19658799%2C110866138%2C72980405 HTTP/1.1" 200 44904
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=148813790%2C92279412%2C87965401%2C759086%2C19130243%2C6471552%2C81243830%2C50007439%2C7204872%2C131895544%2C66337802%2C76945229%2C65216963%2C126807154%2C48827495%2C69242337%2C142960585%2C102435693%2C16326597%2C82061776%2C23345806%2C16785114%2C85891683%2C70073041%2C2579581%2C128586280%2C70967102%2C90302363%2C102094084%2C23813903%2C128637475%2C131618749%2C55427677%2C137103283%2C132570884%2C133373873%2C132570786%2C9190572%2C71318604%2C15211286%2C14609257%2C111741010%2C84896807%2C130584194%2C34342704%2C71063592%2C112848373%2C117637229%2C13189592%2C25082055%2C117760933%2C72896802%2C56919266%2C62336304%2C115431024%2C116601876%2C28588050%2C57107167%2C43357303%2C39920393%2C17257780%2C78958491%2C15665633%2C9337222%2C114397169%2C112577291%2C11898872%2C17351332%2C58823274%2C56423575%2C14396204%2C54537813%2C16959212%2C80589255%2C22195171%2C20717743%2C103130607%2C19076221%2C42375959%2C102272704%2C7056162%2C106539033%2C75391358%2C105555355%2C54564878%2C97665991%2C53432418%2C89572183%2C103623513%2C62186451%2C18566947%2C100670912%2C24552780%2C15279023%2C80299574%2C40594806%2C30053194%2C32321222%2C4364851%2C95430965 HTTP/1.1" 200 45211
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=11927992%2C58373903%2C91629044%2C21996011%2C3397941%2C59529483%2C4371501%2C23560360%2C14527214%2C41269575%2C9555262%2C14098967%2C66430613%2C20969190%2C82381110%2C52227709%2C58117086%2C15973392%2C812920%2C78322520%2C64244883%2C67039063%2C11872442%2C35524594%2C40594059%2C33529068%2C32349792%2C3346971%2C40868080%2C36387657%2C36389125%2C3389621%2C4412471%2C28347911%2C45782588%2C46558857%2C19201821%2C71876190%2C12630512%2C16598186%2C14706299%2C64220324%2C66544069%2C3906501%2C3455631%2C11923732%2C10884702%2C58703917%2C14848589%2C14610444%2C51797797%2C50830949%2C12453012%2C46219856%2C18920257%2C18412495%2C10848412%2C29710616 HTTP/1.1" 200 26072
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/home_timeline.json?count=60&include_entities=True&since_id=410830352223961088 HTTP/1.1" 200 6008
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/mentions_timeline.json?count=60&include_entities=True&since_id=409812431511515136 HTTP/1.1" 200 28
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/direct_messages.json?count=60&include_entities=True&since_id=409145420842299392 HTTP/1.1" 200 28
[Richzendy@olivaw SPECS]$ turpial -d
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/**init**.py:122: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
loaded the Generic plugin 
DEBUG:AppConfig:Started
DEBUG:AppConfig:CONFIG_FILE: /home/Richzendy/.config/turpial/config
DEBUG:AppConfig:FILTERS_FILE: /home/Richzendy/.config/turpial/filtered
DEBUG:AppConfig:FRIENDS_FILE: /home/Richzendy/.config/turpial/friends
DEBUG:AppConfig:Loaded configuration
DEBUG:Controller:Starting Turpial 3.0-b2
DEBUG:change me:Started
DEBUG:AccountConfig:CACHEDIR: /home/Richzendy/.cache/turpial/Richzendy-twitter/images
DEBUG:AccountConfig:CONFIGFILE: /home/Richzendy/.config/turpial/accounts/Richzendy-twitter/config
DEBUG:AccountConfig:Loaded configuration
DEBUG:TurpialHTTP:Validated SSL cert for host: api.twitter.com
INFO:urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/account/verify_credentials.json HTTP/1.1" 200 977
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/lists/list.json?screen_name=Richzendy HTTP/1.1" 200 881
--Created timer for Richzendy-twitter-timeline every 300000 sec
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
--Created timer for Richzendy-twitter-replies every 300000 sec
--Created timer for Richzendy-twitter-directs every 300000 sec
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/home_timeline.json?count=60&include_entities=True HTTP/1.1" 200 26301
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/mentions_timeline.json?count=60&include_entities=True HTTP/1.1" 200 17866
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/direct_messages.json?count=60&include_entities=True HTTP/1.1" 200 12288
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
DEBUG:urllib3.connectionpool:"GET /1.1/friends/ids.json?cursor=-1 HTTP/1.1" 200 3745
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=1412749064%2C2188640280%2C34196832%2C191158687%2C1465991160%2C504737648%2C86368811%2C204072441%2C92173536%2C432751812%2C18344450%2C100731315%2C187085548%2C18996060%2C96799379%2C555928038%2C1546823898%2C559882002%2C142075658%2C199569043%2C83471831%2C32139177%2C1059506833%2C221617799%2C166255930%2C20777992%2C101329724%2C493171168%2C46670078%2C326162536%2C147274572%2C324511975%2C1225314666%2C1276625588%2C63263205%2C79327561%2C14136690%2C85976325%2C458025085%2C14424151%2C133086921%2C63585592%2C305957356%2C73322452%2C551208828%2C13334762%2C14132674%2C32499999%2C199760435%2C977065164%2C40112868%2C232730257%2C39184406%2C21975149%2C1857421%2C53932701%2C57440969%2C23313894%2C14266199%2C25903489%2C1077310099%2C18780270%2C86786657%2C16690810%2C172210678%2C42317616%2C972651%2C92615439%2C240455281%2C1105348578%2C189178882%2C861275917%2C140620659%2C21767412%2C12470382%2C184619338%2C201789953%2C16254468%2C34507577%2C186108816%2C333668789%2C280507552%2C596963130%2C448118032%2C39774237%2C24390692%2C867903643%2C48001264%2C109296506%2C14916839%2C86556093%2C42719222%2C103862663%2C103690811%2C11858232%2C17456270%2C435119060%2C90572703%2C163353201%2C602151203 HTTP/1.1" 200 44929
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=565754571%2C80440340%2C14375294%2C26981455%2C82269962%2C344253343%2C95060522%2C738796448%2C326658079%2C144988772%2C190681215%2C213630712%2C314489263%2C71544889%2C701308015%2C3389221%2C117843976%2C20718994%2C3906191%2C434597929%2C486013940%2C38801267%2C409181411%2C729364148%2C217721601%2C64729645%2C587771871%2C14949454%2C16960753%2C115969204%2C239531667%2C109943488%2C134530196%2C142359326%2C41137418%2C41746908%2C75173200%2C129010299%2C111677646%2C63484454%2C6035252%2C44966220%2C81032548%2C13231902%2C15473958%2C494883886%2C389661845%2C37745226%2C142042291%2C27992505%2C395375443%2C109442071%2C3756831%2C100562129%2C72625007%2C501300140%2C3473621%2C146255863%2C87010330%2C115549104%2C98459553%2C141412729%2C99349204%2C99926444%2C124615143%2C48434822%2C138892116%2C112278793%2C110764615%2C105901957%2C132167584%2C110518778%2C57785152%2C41057207%2C55141937%2C51759473%2C48918861%2C79290691%2C47106499%2C54574413%2C16351784%2C9929622%2C6351662%2C284069689%2C64886054%2C101949871%2C258400748%2C107866555%2C133577765%2C34259816%2C41617215%2C471089948%2C19400946%2C376009267%2C17501369%2C128309221%2C48850329%2C140518868%2C611986351%2C139202123 HTTP/1.1" 200 44840
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=146645130%2C123966801%2C14666205%2C57240601%2C114963606%2C171280977%2C255170447%2C544991457%2C14749606%2C191456848%2C469967838%2C317647291%2C154604973%2C297057211%2C75935380%2C127725981%2C28137831%2C278497176%2C18036676%2C82980990%2C195187948%2C151150589%2C168786120%2C33905807%2C190361879%2C94371793%2C77687778%2C64734835%2C254842187%2C75202953%2C137575942%2C16634447%2C98940507%2C802225%2C19239012%2C106281683%2C6234112%2C37409779%2C14948297%2C81010295%2C75298997%2C109153351%2C403708031%2C352708517%2C82820185%2C512451359%2C233724009%2C113211856%2C141826985%2C24475055%2C86070281%2C50396648%2C91333167%2C364326108%2C108378201%2C15051237%2C133069590%2C223663165%2C356565711%2C21036948%2C352591588%2C145292729%2C16843780%2C302666251%2C305708406%2C28733664%2C286802800%2C8187772%2C166326763%2C132021364%2C247360761%2C87294312%2C2142731%2C107937354%2C344807685%2C354847710%2C125112029%2C69778345%2C112256767%2C43270079%2C74924780%2C147337190%2C429982903%2C18847100%2C438372590%2C287239681%2C280625032%2C25944230%2C134580098%2C137369649%2C133937393%2C14475836%2C8859592%2C109973880%2C19781777%2C312557169%2C313213055%2C105172811%2C4631911%2C387835054 HTTP/1.1" 200 46914
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=42289753%2C216803497%2C120909767%2C109490409%2C33656504%2C362129835%2C95503190%2C20498634%2C92412832%2C172326616%2C14936115%2C169740097%2C118566907%2C167234557%2C53175280%2C343476787%2C113555653%2C137520613%2C107280460%2C43184852%2C201718078%2C227900705%2C106857212%2C92623648%2C377553478%2C15819114%2C17615818%2C30036321%2C100668146%2C317118851%2C46428661%2C21510859%2C171790657%2C152103597%2C96858210%2C272276748%2C87347666%2C140954884%2C49743410%2C157576728%2C109151290%2C144127970%2C6726812%2C75040988%2C52525000%2C81876543%2C17508703%2C71701378%2C52418179%2C103936036%2C93557595%2C40049363%2C15155074%2C134252342%2C43966234%2C92352578%2C14083717%2C349076987%2C189212327%2C199326456%2C143445588%2C19594084%2C130224931%2C197100056%2C40801385%2C11911482%2C12652322%2C331680822%2C149934894%2C134521516%2C329573882%2C119404822%2C66747949%2C258005752%2C166425171%2C246406125%2C45792999%2C50880662%2C97874696%2C328862475%2C69971360%2C84883286%2C64444374%2C60382263%2C138879861%2C113400425%2C234077217%2C97036822%2C17228304%2C50770963%2C66616335%2C77937874%2C319437179%2C150621067%2C52706187%2C214745281%2C142085524%2C226769946%2C269068169%2C137107693 HTTP/1.1" 200 44134
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=89583501%2C209394202%2C19072360%2C314137206%2C5766592%2C264381957%2C12101432%2C90393610%2C248112009%2C51860842%2C16627617%2C237635943%2C10496822%2C305631241%2C13231382%2C126117031%2C136515437%2C141433743%2C216878982%2C254632929%2C190697853%2C136661793%2C49848433%2C95736901%2C165898835%2C97067702%2C16617691%2C17013058%2C294475107%2C52433558%2C68703337%2C202279491%2C115555681%2C85408645%2C146713993%2C12841212%2C262599386%2C279191509%2C197122574%2C278559186%2C63239078%2C134569854%2C153128720%2C273050108%2C271032076%2C143979606%2C147584062%2C23418362%2C137002089%2C39292581%2C18960133%2C26264191%2C77926072%2C259517216%2C83204594%2C232626428%2C16707257%2C220299921%2C18004094%2C2764671%2C43564298%2C213423255%2C52129275%2C192264798%2C93984855%2C108734782%2C102804859%2C200936973%2C16242076%2C233820603%2C218019997%2C168357090%2C143573660%2C113443277%2C85147950%2C65366725%2C227974149%2C122668309%2C16045370%2C177926099%2C9882482%2C135025066%2C201585441%2C92637150%2C148553075%2C176693595%2C215282594%2C17790274%2C211188020%2C39190538%2C133841947%2C62837451%2C190263396%2C25413219%2C7001322%2C17337554%2C35649630%2C146193928%2C8411122%2C59424092 HTTP/1.1" 200 41797
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=14141651%2C116000289%2C128361959%2C194202831%2C812868%2C85426644%2C134664821%2C157115760%2C78366880%2C139594044%2C195558054%2C85361349%2C108338250%2C14877781%2C14204109%2C73809715%2C125146065%2C18525312%2C90448718%2C89717019%2C72751020%2C15072316%2C13959882%2C11945072%2C53458268%2C11545%2C14215272%2C138043198%2C114490934%2C93617072%2C83977792%2C6912112%2C20569760%2C72580043%2C803808%2C53294902%2C66763332%2C106124703%2C48780993%2C98679403%2C112036196%2C101787048%2C54973589%2C71040368%2C55981836%2C134811903%2C65297502%2C149142188%2C35950442%2C109290243%2C54535649%2C17435044%2C76103661%2C11287692%2C147279218%2C165751353%2C108518199%2C91120943%2C82288053%2C76657294%2C66029909%2C62203393%2C58809331%2C55880477%2C54713295%2C47559430%2C40284770%2C26767736%2C18973753%2C18948653%2C17633909%2C16362921%2C15918218%2C14966270%2C14888223%2C14744978%2C14602223%2C14429811%2C14134831%2C9383442%2C6003702%2C777466%2C102763917%2C94524695%2C34970551%2C138250994%2C46858161%2C15666038%2C148751006%2C104975604%2C85091976%2C99199905%2C50871388%2C90944663%2C34499885%2C40915061%2C6508842%2C19658799%2C110866138%2C72980405 HTTP/1.1" 200 44767
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=148813790%2C92279412%2C87965401%2C759086%2C19130243%2C6471552%2C81243830%2C50007439%2C7204872%2C131895544%2C66337802%2C76945229%2C65216963%2C126807154%2C48827495%2C69242337%2C142960585%2C102435693%2C16326597%2C82061776%2C23345806%2C16785114%2C85891683%2C70073041%2C2579581%2C128586280%2C70967102%2C90302363%2C102094084%2C23813903%2C128637475%2C131618749%2C55427677%2C137103283%2C132570884%2C133373873%2C132570786%2C9190572%2C71318604%2C15211286%2C14609257%2C111741010%2C84896807%2C130584194%2C34342704%2C71063592%2C112848373%2C117637229%2C13189592%2C25082055%2C117760933%2C72896802%2C56919266%2C62336304%2C115431024%2C116601876%2C28588050%2C57107167%2C43357303%2C39920393%2C17257780%2C78958491%2C15665633%2C9337222%2C114397169%2C112577291%2C11898872%2C17351332%2C58823274%2C56423575%2C14396204%2C54537813%2C16959212%2C80589255%2C22195171%2C20717743%2C103130607%2C19076221%2C42375959%2C102272704%2C7056162%2C106539033%2C75391358%2C105555355%2C54564878%2C97665991%2C53432418%2C89572183%2C103623513%2C62186451%2C18566947%2C100670912%2C24552780%2C15279023%2C80299574%2C40594806%2C30053194%2C32321222%2C4364851%2C95430965 HTTP/1.1" 200 45245
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/users/lookup.json?user_id=11927992%2C58373903%2C91629044%2C21996011%2C3397941%2C59529483%2C4371501%2C23560360%2C14527214%2C41269575%2C9555262%2C14098967%2C66430613%2C20969190%2C82381110%2C52227709%2C58117086%2C15973392%2C812920%2C78322520%2C64244883%2C67039063%2C11872442%2C35524594%2C40594059%2C33529068%2C32349792%2C3346971%2C40868080%2C36387657%2C36389125%2C3389621%2C4412471%2C28347911%2C45782588%2C46558857%2C19201821%2C71876190%2C12630512%2C16598186%2C14706299%2C64220324%2C66544069%2C3906501%2C3455631%2C11923732%2C10884702%2C58703917%2C14848589%2C14610444%2C51797797%2C50830949%2C12453012%2C46219856%2C18920257%2C18412495%2C10848412%2C29710616 HTTP/1.1" 200 26067

INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/home_timeline.json?count=60&include_entities=True&since_id=410831913776349184 HTTP/1.1" 200 7124
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/mentions_timeline.json?count=60&include_entities=True&since_id=409812431511515136 HTTP/1.1" 200 28
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/direct_messages.json?count=60&include_entities=True&since_id=409145420842299392 HTTP/1.1" 200 28
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/home_timeline.json?count=60&include_entities=True&since_id=410833134616588288 HTTP/1.1" 200 8738
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
DEBUG:urllib3.connectionpool:"GET /1.1/statuses/mentions_timeline.json?count=60&include_entities=True&since_id=409812431511515136 HTTP/1.1" 200 28
INFO:urllib3.connectionpool:Starting new HTTP connection (1): api.twitter.com
DEBUG:urllib3.connectionpool:"GET /1.1/direct_messages.json?count=60&include_entities=True&since_id=409145420842299392 HTTP/1.1" 200 28

**Comment by satanas** [comment]
Great! So, can we consider this bug as fixed?
