### ISSUE TITLE
Actions over a single tweet

### ISSUE THREAD

**Issue by satanas** [satanas/Turpial#247]
- Copy link URL to share
- View tweet on twitter

**Comment by dingens** [comment]
I'd propose to implement that in the way that the timestamp of the link is a link to https://twitter.com/username/status/123 (with a right click menu that includes "copy url").
That's how it's implemented in most other clients (and the timestamp being the link of an item is common practice all over the internet)

**Comment by satanas** [comment]
Implemented on commit 063b5a6
