### ISSUE TITLE
Display images in browser, with image preview or inline (on-click)

### ISSUE THREAD

**Issue by satanas** [satanas/Turpial#248]

**Comment by nullrend** [comment]
Bump.

This feature is available on pretty much every other client out there, although to beat them the ideal situation would be to provide three options:
1. Disable media preview.
2. Small media preview (I'm thinking aligned to the right, on top of of the action icons. Tweet stays centre-aligned)
3. Big media preview (with the image below the tweet and the action icons below it)

**Comment by satanas** [comment]
I still don't get the small media preview idea. Could you post some mock or screenshot?

**Comment by nullrend** [comment]
Small preview would look a bit like this: http://imgur.com/RiM45wp,dRXfzN0#0
Big media preview would look like this: http://imgur.com/RiM45wp,dRXfzN0#1

When you disable media preview, you would only get a link you can click on to open on a browser.

**Comment by satanas** [comment]
This feature has been implemented but only using the big media preview at the moment. The small media preview will be considered for the next release because it involves much more work. Closing

**Comment by satanas** [comment]
Small preview will be followed in #296
