### ISSUE TITLE
web link in profile window must be clickeable

### ISSUE THREAD

**Issue by Richzendy** [satanas/Turpial#249]
Hi,

This is a improvement bug, web link in profile window must be clickeable and open in a default browser.

![captura de pantalla de 2013-12-11 16 42 56](https://f.cloud.github.com/assets/284522/1728158/d8b4dae2-62a9-11e3-8d5f-467a74ca0ad8.png)

**Comment by satanas** [comment]
Totally agree, thanks for reporting the issue

**Comment by satanas** [comment]
This issue will be followed in #270. Closing
