### ISSUE TITLE
Hora de los mensajes?

### ISSUE THREAD

**Issue by simonbcn** [satanas/Turpial#25]
Las horas de los mensajes me aparecen en formato 12h pero sin indicar am/pm.
De todas formas, eso no debería ser un estándar impuesto por el programa, si no que debería respetar la configuración local. En España se suele usar el formato 24h (mucho más práctico).

**Comment by sebasmagri** [comment]
La hora creo que se muestra directamente como la envía twitter/identi.ca. Si es así, cambiar el formato puede implicar un trabajo de procesamiento adicional.

**Comment by satanas** [comment]
The new Turpial uses relative times like the Twitter web (1m, 30m, 2h) so this issue is no longer valid
