### ISSUE TITLE
Not able to launch main window after clicking on Window close button

### ISSUE THREAD

**Issue by ghostkadost** [satanas/Turpial#250]
I have installed Beta 2 on Ubuntu 13.10 using the unofficial debian package. I have enabled Minimize on Close in my preference. I can see turpial icon in the notification area. But after I click on main window close button, there is no way to retrieve it. The menu options in the notification area only allow to update status etc but I cannot go back to the TL window. Also if I click on Preference menu and then close the preference dialog box, the application stops running.

**Comment by satanas** [comment]
Fixed
