### ISSUE TITLE
Scroll behaviour

### ISSUE THREAD

**Issue by ghostkadost** [satanas/Turpial#251]
By default after the TL is refreshed, scroll bar is placed at the top. This can be very irritating if you let the application run in the background and do some other work and the TL is very active. This makes it difficult to follow any conversation since now you would be reading the tweets that came later. Is it possible to implement something like last seen tweet and keep the scroll bar at that position?

**Comment by satanas** [comment]
Certainly it's very annoying. I'll do my best to address this issue.

Thanks for reporting

**Comment by satanas** [comment]
Fixed in 491f12e
