### ISSUE TITLE
E: invalid-desktopfile

### ISSUE THREAD

**Issue by Richzendy** [satanas/Turpial#253]
I have this error (in verification) when i build a rpm package to Fedora:

turpial.noarch: E: invalid-desktopfile /usr/share/applications/turpial.desktop value "2.0" for key "Version" in group "Desktop Entry" is not a known version

According http://standards.freedesktop.org/desktop-entry-spec/latest/ar01s05.html i will provide this patch:

https://gist.github.com/Richzendy/8173903

**Comment by satanas** [comment]
Thanks bro, I'll apply the patch to fix that file

**Comment by satanas** [comment]
Fixed
