### ISSUE TITLE
GTK interface not available

### ISSUE THREAD

**Issue by Vistaus** [satanas/Turpial#264]
When running the latest Turpial 3 from Git, I can only run it as Qt or CMD but not as GTK. I have python-gtk2 installed. The exact error is:

[vistaus@yoga13 Turpial]$ turpial -i gtk
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
'gtk' is not a valid interface. Availables interfaces are cmd, qt

How to solve this?

**Comment by satanas** [comment]
Right now there is no support for GTK but I'm thinking on develop a GTK interface in the near future
