### ISSUE TITLE
Fonts are too big

### ISSUE THREAD

**Issue by Vistaus** [satanas/Turpial#265]
I'm not sure how, but the fonts are quite big. They seem about 12-13 pt. As it only renders the Qt interface for now, I thought it might be because of my Qt settings but other Qt apps have a way smaller font because I did set it to 10 pt.

**Comment by satanas** [comment]
Could you post a screenshot and tell me about your OS and Qt version?

**Comment by Vistaus** [comment]
Sure. I'm using Arch Linux and I have Qt 4 and 5 installed but Turpial is explicitly using Qt 4 with font settings set to 10pt in Qt4 Config.
It may not be 13 pt as you see in the screenshot but it's definetly bigger than the font in other Qt apps and changing the pt in Qt4 Config doesn't change it in Turpial (whereas it does in other Qt apps) so it's ignoring font settings.
![screenshot from 2014-01-20 15 19 46](https://f.cloud.github.com/assets/1716229/1954807/78237d9c-81de-11e3-97a3-57e4ec3849e8.png)

**Comment by satanas** [comment]
Well, everything looks as it should. Turpial is ignoring Qt font settings right now because I haven't developed any support for it yet and Turpial layout could break out. However I should be supporting that feature soon

**Comment by Vistaus** [comment]
In that case I'll be monitoring Git but holding off on using Turpial as a daily driver for now. Thanks for the good communication.
