### ISSUE TITLE
Clickable links in user profile window

### ISSUE THREAD

**Issue by ashep** [satanas/Turpial#270]
It should be nice to have ability to click on links in user profile window or at least to copy them:
![shot-001](https://f.cloud.github.com/assets/1115657/1995298/3d206634-8502-11e3-8ebf-d83bbae6fa6c.png)

**Comment by satanas** [comment]
You're right, thanks for your report. Besides I should show the expanded link

**Comment by satanas** [comment]
Link is already clickable. The URL is a crap but that should be fixed with the support for entities in libturpial
