### ISSUE TITLE
Failing on startup

### ISSUE THREAD

**Issue by kz9676** [satanas/Turpial#271]
blah@HP-Pavilion:~$ turpial -d
DEBUG::Using gst as sound system
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
DEBUG:AppConfig:Started
DEBUG:Controller:Starting Turpial 3.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/main.py", line 592, in after_core_initialized
    width, height = self.core.get_window_size()
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/worker.py", line 509, in get_window_size
    config['Window']['size'] = "320,480"
KeyError: 'Window'
/usr/lib/python2.7/dist-packages/turpial/ui/qt/main.py:234: GtkWarning: IA__gtk_widget_get_direction: assertion 'GTK_IS_WIDGET (widget)' failed
  self.app.exec_()

**Comment by jhuss** [comment]
I had the same problem, in fedora 20 are available libturpial 1.1.16
I uninstalled and installed directly https://github.com/satanas/libturpial version 1.6.0 and the problem was fixed

**Comment by joickle** [comment]
@jhuss that worked for me too, although I didn't uninstall the old libturpial first.

**Comment by satanas** [comment]
This issue was fixed in [libturpial 1.6.0](http://turpial.org.ve/2014/01/libturpial-got-new-update-1-6-0/). Closing
