### ISSUE TITLE
Will not startup past loading screen

### ISSUE THREAD

**Issue by LiamDawe** [satanas/Turpial#272]
It loads up and says "give me a minute..." with the loading bar.

This is what terminal gave me:
liam@liam-ubuntu:~$ turpial
DEBUG::Using gst as sound system
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
/usr/lib/python2.7/dist-packages/turpial/ui/qt/webview.py:33: GtkWarning: Theme file for DMZ-Black has no directories

  page = self.page()
"sni-qt/28878" WARN  19:18:36.384 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/main.py", line 592, in after_core_initialized
    width, height = self.core.get_window_size()
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/worker.py", line 509, in get_window_size
    config['Window']['size'] = "320,480"
KeyError: 'Window'

**Comment by joickle** [comment]
Same issue here :(

**Comment by jhuss** [comment]
this seems to be the same problem https://github.com/satanas/Turpial/issues/271

**Comment by satanas** [comment]
As @jhuss commented, this issue was fixed in (libturpial 1.6.0)[http://turpial.org.ve/2014/01/libturpial-got-new-update-1-6-0/]. Please upgrade your libturpial version

**Comment by LiamDawe** [comment]
Using this PPA linked by omgubuntu https://launchpad.net/~effie-jayx which has an outdated lib in it.

I have emailed the PPA owner.

**Comment by satanas** [comment]
@liamdawe Yes, PPA should be updated as soon as possible. Efrain Valles should be working on that already
