### ISSUE TITLE
clean all bytecode option fails on opensuse 13.1

### ISSUE THREAD

**Issue by githubrsys** [satanas/Turpial#279]
<code>
turpial -cd
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
DEBUG:Controller:Cleaning da house...
DEBUG:Controller:Deleting /usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/singleton.pyc
Traceback (most recent call last):
  File "/usr/bin/turpial", line 9, in <module>
    load_entry_point('turpial==3.0', 'console_scripts', 'turpial')()
  File "/usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/main.py", line 106, in main
    t = Turpial()
  File "/usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/main.py", line 61, in **init**
    clean_bytecodes(**file**, self.log)
  File "/usr/lib/python2.7/site-packages/libturpial-1.0-py2.7.egg/libturpial/common/tools.py", line 26, in clean_bytecodes
    os.remove(path)
<b>OSError: [Errno 13] Keine Berechtigung: '/usr/lib/python2.7/site-packages/turpial-3.0-py2.7.egg/turpial/singleton.pyc'</b>
</code>
#### Where 'Keine Berechtigung' means 'No Access'

I am running as normal user on openSuse 13.1 with turpial git development branch

**Comment by satanas** [comment]
That's ok. If Turpial was installed using superuser privileges then all files will be under superuser control. You have two options:
1. Install Turpial from sources as it was the development version. This way all files will remain in your selected folder with symlinks to the /usr/lib/python2.7/site-packages directory
2. Run `turpial -cd' using sudo
