### ISSUE TITLE
Se queda colgado al iniciar

### ISSUE THREAD

**Issue by risk0** [satanas/Turpial#28]
repositorio: http://ppa.launchpad.net/effie-jayx/turpial-devel/ubuntu
Linux 2.6.32-25-generic
Ubuntu 10.04 - 64bit
GNOME 2.30.2

inicio en modo debug y se queda en gris la ventana de turpial sacando lo siguiente en terminal:

fran@fran-laptop:~$ turpial -d
DEBUG:Sound:Iniciado
DEBUG:Gtk:Cargado modo GTK Simple
DEBUG:Services:Iniciado
DEBUG:API:Iniciado
DEBUG:Controller:Iniciando Turpial v1.4.9-a1
DEBUG:Config:CACHEDIR: /home/fran/.cache/turpial/twitter/Fran_Vila/images
DEBUG:Config:CONFIGFILE: /home/fran/.config/turpial/twitter/Fran_Vila/config
DEBUG:Config:MUTEDFILE: /home/fran/.config/turpial/twitter/Fran_Vila/muted
DEBUG:Config:Cargando archivo
DEBUG:Config:Leyendo sección Auth
DEBUG:API:Solicitando autenticacion
DEBUG:Twitter:Iniciado
DEBUG:TurpialHTTP:No se detectaron proxies en el sistema
DEBUG:Twitter:Iniciando autenticacion segura
DEBUG:TwitterHTTP:URI: http://api.twitter.com/1/account/verify_credentials.json
DEBUG:Config:CACHEDIR: /home/fran/.cache/turpial/twitter/Fran_Vila/images
DEBUG:Config:CONFIGFILE: /home/fran/.config/turpial/twitter/Fran_Vila/config
DEBUG:Config:MUTEDFILE: /home/fran/.config/turpial/twitter/Fran_Vila/muted
DEBUG:Config:Cargando archivo
DEBUG:Twitter:Descargando Listas del usuario
DEBUG:TwitterHTTP:URI: http://api.twitter.com/1/Fran_Vila/lists.json
DEBUG:TwitterHTTP:URI: http://api.twitter.com/1/Fran_Vila/lists/subscriptions.json
DEBUG:Twitter:--Descargadas 15 listas
DEBUG:Gtk:Cargando ventana principal
DEBUG:Gtk:Actualizando configuracion
DEBUG:Gtk:Cambiando a modo single ((320, 480))
DEBUG:Gtk:--Creado timer de Timeline cada 3 min
DEBUG:Gtk:--Creado timer de Replies cada 10 min
DEBUG:Gtk:--Creado timer de Directs cada 15 min

**Comment by satanas** [comment]
Deprecated
