### ISSUE TITLE
[enhancement] GUI - support rows per column

### ISSUE THREAD

**Issue by githubrsys** [satanas/Turpial#282]
It would be awesome if you could drag and drop the informational stream colums, so to have rows. 
- Pick the header of a certain timeline or favorites column 
- move it 50px near top or bottom of another column 
- an visual indication (like a transparent color block that makes an 20px margin spacer) appears, that you can drop that column.
- now drop it there
- now you have 2 rows and preserved some space
- the rows height should take half height of the former chosen column
- the height should be adjustable by picking the line between the two timelines (or whatever is there)
- make these settings then persistent
## I like the Idea.

What about you?

**Comment by satanas** [comment]
This idea requires too much work that I prefer invest in new features. Closing
