### ISSUE TITLE
Indicate all tweets that were loaded with the last update

### ISSUE THREAD

**Issue by Faldrian** [satanas/Turpial#284]
I like twitter clients that show me what is new since the last time I looked at the window. But I also don't like to "mark all as read" with a button - too much interaction with the programm itself.

So you have to see what is new just by looking hat it. My idea would be to show a little border on each tweet (on the left maybe). The color of the border of new tweets per column changes with each update.

Example: first update: all new tweets have red border. Next update: 3 tweets are loaded, so there are 3 tweets with green border and below them the old tweets with their red border remain unchanged.
You can probably work with just two alternating colors, but maybe (depening on update speed) there should be 5 to iterate.

As a user I probably remember which color the last update had and can see all tweets that are new. Or with just two colors I only have to look where the color of the border changes.

**Comment by satanas** [comment]
This was implemented using only one color. You will be able to see the newest tweets since the last update. More than that would be too complex for other users
