### ISSUE TITLE
Turpial doesn't start anymore with Python 3

### ISSUE THREAD

**Issue by Vistaus** [satanas/Turpial#297]
When using Turpial from the Git development branch, it installs fine along with libturpial from Git. But when launching Turpial, it just doesn't launch. The output I get is:

vistaus@yoga13:~/fromsvngit/Turpial$ turpial
Traceback (most recent call last):
  File "/usr/bin/turpial", line 9, in <module>
    load_entry_point('turpial==3.4.0-dev', 'console_scripts', 'turpial')()
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2088, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python3.3/site-packages/turpial-3.4.0_dev-py3.3.egg/turpial/main.py", line 68
    print "'%s' is not a valid interface. Availables interfaces are %s" % (
                                                                      ^
SyntaxError: invalid syntax
vistaus@yoga13:~/fromsvngit/Turpial$ 

I'm using Arch Linux with all the dependencies installed. It used to work before.

**Comment by satanas** [comment]
You're installing with python 3.3 and Turpial needs python 2.7. Try installing using Python 2.7. This issue will be closed

> File "/usr/lib/python3.3/site-packages/turpial-3.4.0_dev-py3.3.egg/turpial/main.py

**Comment by Vistaus** [comment]
I guess you didn't read? It used to work before. As in: a couple of commits ago.

**Comment by satanas** [comment]
Yes I did. But there is no official support at the moment for Turpial under python 3.x

**Comment by milmazz** [comment]
@Vistaus Looking at your initial output I see the error is the `print` statement in the file `turpial/main.py` at line 68, I think you have two options until the error get fixed:
- Comment the line or
- Adjust your `print` statement to `print()`

Hopefully this will fix the error, but, as @satanas says, there is no official support for Python 3 yet :weary:

**Comment by Vistaus** [comment]
Well, then I do wonder why it did work a couple of commits ago...

Anyway: thanks milmazz for the workaround.
