### ISSUE TITLE
Al escribir una dirección de correo.

### ISSUE THREAD

**Issue by encels** [satanas/Turpial#3]
Al momento de mostrar un tweet que tenga una direccion de correo electronico 
muestra el provedor de correo como un usuario, es decir todo lo que esta 
despues de la @ lo marca como un link de usuario, 

Por ejemplo: 

encels@gmail.com  marcaria como enlance y como usuario a @gmail 

Supongo que solo lo debe marcar si la @ viene justo despues de un espacio y 
no antecedida  por una letra.

**Comment by satanas** [comment]
Fixed
