### ISSUE TITLE
Turpial keeps crashing: no attribute 'ui'

### ISSUE THREAD

**Issue by Vistaus** [satanas/Turpial#300]
vistaus@yoga13:~/fromsvngit/libturpial$ turpial
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
Traceback (most recent call last):
  File "/usr/bin/turpial", line 9, in <module>
    load_entry_point('turpial==3.4.7-dev', 'console_scripts', 'turpial')()
  File "/usr/lib/python2.7/site-packages/turpial-3.4.7_dev-py2.7.egg/turpial/main.py", line 106, in main
    t = Turpial()
  File "/usr/lib/python2.7/site-packages/turpial-3.4.7_dev-py2.7.egg/turpial/main.py", line 81, in **init**
    self.ui.show_main()
AttributeError: Turpial instance has no attribute 'ui'
vistaus@yoga13:~/fromsvngit/libturpial$

I'm using Arch Linux with Turpial from Git. I expect code to break sometimes given that it's upstream Git code, but it's been broken for a while now. I've installed it with Python 2 and all the dependencies are installed.

**Comment by satanas** [comment]
Hello, did check this dependencies list? http://wiki.turpial.org.ve/dev:dependencies. It looks like Turpial is trying to load a non-Qt interface

**Comment by Vistaus** [comment]
All the dependencies are installed and a couple of commits ago Turpial launched just fine.

**Comment by satanas** [comment]
Could you run this:

``` bash
python -c "from libturpial import VERSION; print VERSION"
```

And this:

``` bash
python -c "from turpial import VERSION; print VERSION"
```

And post the output of both commands.

Just to be sure, are you using the steps pointed in the wiki? http://wiki.turpial.org.ve/dev:installation

**Comment by Vistaus** [comment]
vistaus@yoga13:~/fromsvngit/qupzilla$ python2 -c "from turpial import VERSION; print VERSION"
3.5.5-dev
vistaus@yoga13:~/fromsvngit/qupzilla$ python2 -c "from libturpial import VERSION; print VERSION"
1.7.0-b2
vistaus@yoga13:~/fromsvngit/qupzilla$ 

I followed the mentioned steps.

**Comment by Vistaus** [comment]
I really don't know what I'm supposed to do... I wanna use the Git version again, like I used to.

**Comment by satanas** [comment]
This is really really weird. Let's try cleaning all the bytecodes. Execute:

`$ turpial -c`

And try again. I'm clueless about what's happening there. If that doesn't work, the last thing that comes to my mind is uninstall everything, clean and reinstall. Check steps at the bottom of the installation wiki page to see how to uninstall everything http://wiki.turpial.org.ve/dev:installation#uninstall_everything

**Comment by Vistaus** [comment]
Did turpial -c, it cleaned everything (or so it said) and started Turpial again. But still:

vistaus@yoga13:~$ turpial
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
DEBUG::Using gst as sound system
/usr/lib/python2.7/site-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
Traceback (most recent call last):
  File "/usr/bin/turpial", line 9, in <module>
    load_entry_point('turpial==3.5.9-dev', 'console_scripts', 'turpial')()
  File "/usr/lib/python2.7/site-packages/turpial-3.5.9_dev-py2.7.egg/turpial/main.py", line 106, in main
    t = Turpial()
  File "/usr/lib/python2.7/site-packages/turpial-3.5.9_dev-py2.7.egg/turpial/main.py", line 81, in **init**
    self.ui.show_main()
AttributeError: Turpial instance has no attribute 'ui'
vistaus@yoga13:~$

I also tried removing everything and starting from scratch. But even then it still crashes with that same error :(

**Comment by satanas** [comment]
Can you post the content of your /usr/local/bin/turpial?

`cat /usr/local/bin/turpial`

**Comment by Vistaus** [comment]
And now I removed and installed Turpial again for the gazillionth time and magically it started working. Thanks for the help! :)

**Comment by satanas** [comment]
Hahaha. You're welcome! I was running out of ideas, probably was some kind of mixing between your previous installation of Turpial with python3 and the current one
