### ISSUE TITLE
KeyError: 'Window' at startup

### ISSUE THREAD

**Issue by Majki** [satanas/Turpial#305]
I have latest Turpial from PPA on Saucy 13.10 64bit. After startin app it hangs on splash screen:
http://i.imgur.com/KcQdLyo.png

And get this in terminal:

michal@skynet ~ $ turpial 
DEBUG::Using gst as sound system
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/**init**.py:127: RuntimeWarning: PyOS_InputHook is not available for interactive use of PyGTK
  set_interactive(1)
"sni-qt/19685" WARN  18:12:42.102 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/main.py", line 592, in after_core_initialized
    width, height = self.core.get_window_size()
  File "/usr/lib/python2.7/dist-packages/turpial/ui/qt/worker.py", line 509, in get_window_size
    config['Window']['size'] = "320,480"
KeyError: 'Window'

**Comment by satanas** [comment]
Thanks for reporting. This issue was fixed in the current development version of libturpial. Packages should update soon in PPA

**Comment by Majki** [comment]
That escalated quickly! :D When we get working Turpial in PPA then? :) I would be more than happy to help with feeedback on Ubuntu 13.10.

**Comment by satanas** [comment]
Hahaha, I'm pretty efficient ;) Well, we need to release a new version of libturpial and it's currently on beta, if everything goes fine by the end of the month there should be a stable release and then maintainers can work on update packages. For more information check http://turpial.org.ve/2014/03/new-beta-release-for-libturpial-1-7-0-b3/.

And if you feel daredevil you can try the development version http://wiki.turpial.org.ve/dev:installation ;)

**Comment by Majki** [comment]
Cool - got tarball but I'm not sure if I want to run sudo python setup.py install - not sure how to remove this dev stuff when PPA will be updated. Would be awesome if I could install it locally - this is "just in folder" and run dev version from there.

There is almost no GTK-friendly twitter clients, or Linux-friendly in general :D So I'm happt that Turpial is actively maintened :)

**Comment by satanas** [comment]
You don't need to run sudo python setup.py install, instead you can run:

`sudo python setup.py develop`

This won't copy or install Turpial in your system but keep the code in the folder you are and creates a symlink to /usr/lib/python2.7/site-packages to make it work. After that you can follow the steps at the bottom of the wiki page I just give you to uninstall everything and leave it shiny clean

**Comment by Majki** [comment]
Amazing voodoo stuff :-)

I have a problem with running it though.

michal@skynet ~/Aplikacje/libturpial-1.7.0-b3 $ sudo python setup.py develop
[sudo] password for michal: 
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'develop'

Im on Linux Mint 16 AKA Ubuntu 13.10.

**Comment by satanas** [comment]
Yep, you need setuptools package (or maybe python-setuptools according your OS) to make it work

**Comment by Majki** [comment]
Thanks, seems liek stuff is working

michal@skynet ~/Aplikacje/libturpial-1.7.0-b3 $ sudo python setup.py develop
running develop
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running egg_info
creating libturpial.egg-info
writing requirements to libturpial.egg-info/requires.txt
writing libturpial.egg-info/PKG-INFO
writing top-level names to libturpial.egg-info/top_level.txt
writing dependency_links to libturpial.egg-info/dependency_links.txt
writing manifest file 'libturpial.egg-info/SOURCES.txt'
reading manifest file 'libturpial.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'libturpial.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python2.7/dist-packages/libturpial.egg-link (link to .)
Adding libturpial 1.7.0-b3 to easy-install.pth file

Installed /home/michal/Aplikacje/libturpial-1.7.0-b3
Processing dependencies for libturpial==1.7.0-b3
Searching for requests==1.2.3
Best match: requests 1.2.3
Adding requests 1.2.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for simplejson==3.3.0
Best match: simplejson 3.3.0
Adding simplejson 3.3.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for oauth==1.0.1
Best match: oauth 1.0.1
Adding oauth 1.0.1 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for distribute==0.6.37
Best match: distribute 0.6.37
Adding distribute 0.6.37 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for libturpial==1.7.0-b3
michal@skynet ~/Aplikacje/libturpial-1.7.0-b3 $ ls
AUTHORS    COPYING   ez_setup.py   libturpial.egg-info  README.rst        setup.py                     tox.ini
build      docs      ez_setup.pyc  MANIFEST.in          requirements.txt  setuptools-0.6c11-py2.7.egg
ChangeLog  examples  libturpial    pylintrc             setup.cfg         tests

Where is bin file? :)

**Comment by Majki** [comment]
Okay I followed wiki and installed Turpial as well as libturpial :p 

michal@skynet ~/Aplikacje $ git clone git://github.com/satanas/Turpial.git

and after that:
michal@skynet ~/Aplikacje/Turpial $ ./setup.py 
Traceback (most recent call last):
  File "./setup.py", line 11, in <module>
    from babel.messages import frontend as babel
ImportError: No module named babel.messages

michal@skynet ~/Aplikacje/Turpial $ ls
AUTHORS    ez_setup.py  README.rst        setup.py     turpial
ChangeLog  MANIFEST.in  requirements.txt  THANKS       turpial.desktop
COPYING    pylintrc     setup.cfg         TRANSLATORS

**Comment by satanas** [comment]
Yup, did you install the dependencies? There is a link on the installation page http://wiki.turpial.org.ve/dev:dependencies

**Comment by Majki** [comment]
Works like a charm! THANK YOU

**Comment by satanas** [comment]
No problem. I'm glad it worked :)
