### ISSUE TITLE
Queue breaks with message that contains 'Enter'

### ISSUE THREAD

**Issue by satanas** [satanas/Turpial#308]
Traceback (most recent call last):
  File "/home/satanas/proyectos/turpial2/turpial/ui/qt/queue.py", line 135, in __on_timeout
    if len(self.base.core.list_statuses_queue()) == 0:
  File "/home/satanas/proyectos/turpial2/turpial/ui/qt/worker.py", line 430, in list_statuses_queue
    account_id, message = line.strip().split("\1")
ValueError: need more than 1 value to unpack

**Comment by VoidFox** [comment]
no idea what that gibberish means, but still gonna complain ;p
after adding a multiple line message to the queue, the queue file adds this :

random-twitter[ random mark i couldnt copy ]dfaljsdfjaöldsjfkalsjdf
klasdjfklasdjflöajsdf

once that is in the queue file the "Messages Queue" in the app doesnt open anymore

**Comment by satanas** [comment]
Yep, that's exactly the error I reported ;)

Thanks for confirming

**Comment by satanas** [comment]
Fixed
