### ISSUE TITLE
[request] Read/unread diversifications

### ISSUE THREAD

**Issue by Majki** [satanas/Turpial#309]
I would love to have tweets in two colors/shapes/whatever - one for "new" tweets and one for "read" ones.

NEW tweet = tweet shown on the screenfor the first time until it becames "read" one 
READ tweet = app has been minimzed/closed, tweet was clicked manually/clicked "read all"

It would make simpler and quicker for user to see which column has new tweets.

**Comment by satanas** [comment]
This issue will be followed in #284 to avoid duplication. Closing
