### ISSUE TITLE
[request] Support for instagram preview

### ISSUE THREAD

**Issue by Majki** [satanas/Turpial#311]
Images in twitter that are linking to Instagram are not previewed. Would be cool to have that working - if this is possible ofc.

**Comment by satanas** [comment]
Instagram API is not very friendly about this, that's the reason why twitter doesn't show them. We can't do anything about it. Closing

**Comment by satanas** [comment]
Well, at least about inline preview. Preview with click is already working for instagram. So don't worry :)
