### ISSUE TITLE
Please create an AppData file for Turpial

### ISSUE THREAD

**Issue by hughsie** [satanas/Turpial#333]
Please consider writing and installing an AppData file with the application description and some screenshots, else Turpial looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by satanas** [comment]
Hi @hughsie, thanks for your comments. I'll add the AppData file and the screenshot as you suggest, so Turpial looks nice in the software centers :+1:

**Comment by satanas** [comment]
This has been planned for the next stable release

**Comment by satanas** [comment]
Implemented on development version. For more info check commit 2474e5dc

**Comment by hughsie** [comment]
File looks good, but one major issue; the new file needs to be installed in share/appdata not share/applications! Thanks.

**Comment by satanas** [comment]
Is not the same place than the .desktop file?

**Comment by hughsie** [comment]
Nope, different location: https://github.com/hughsie/createrepo_as/blob/master/src/plugins/cra-plugin-appdata.c#L84

**Comment by satanas** [comment]
Got it! Thanks for the heads up. It's fixed now 25277ab
