### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by JPRuehmann** [satanas/Turpial#350]
Hello
Is there a way to change the Collors in Turpial?
I´m usin Kubuntu 14.04 Turpial 3 and QTCurve, with Dark Colors.
Thanks,
JPR

**Comment by satanas** [comment]
Hello @JPRuehmann, for the development version there is already support for a dark theme, you can check a screenshot [here](https://twitter.com/TurpialVe/status/473242757205852160).

If you want to test it I encourage you to install the development version following the steps on the [wiki page](wiki.turpial.org.ve/dev:installation).

Cheers
