### ISSUE TITLE
Statuses per columns: should not be hard coded

### ISSUE THREAD

**Issue by djatlantic** [satanas/Turpial#356]
I just started to use Turpial and it is great but it has a hard coded limit on how many messages it can display in a column.

I think that Turpial is even better if user can dynamically set this or just let the users to request for the next batch of messages until some upper limits that are set by Twitter.

Thanks.

**Comment by satanas** [comment]
The number of messages per column is not hard coded, you can change it in the preferences windows. For some columns like favorites and lists, I've not implemented pagination so the Twitter API only returns the first 20 tweets for each one

**Comment by sebotic** [comment]
Installed Turpial recently and really like it, but I depend on my lists. Do you plan on implementing pagination, because it would really be awesome, if I could have more than 20 tweets in my very busy list?

Thanks!

**Comment by satanas** [comment]
Yes, pagination is planned. I hope to implement it soon
