### ISSUE TITLE
Debian Can´t create Twitter Account

### ISSUE THREAD

**Issue by JPRuehmann** [satanas/Turpial#363]
Hello
I have the following Problem on my Laptop
I can´t create a Twitter account.
If I Clic New, Twitter it Says Problems registering new account.
and on the Terminal it says KeyError: 'oauth_token'.
How can I make it work?
Thanks,
JPR

**Comment by satanas** [comment]
Hi, which version of turpial and libturpial are you using?

**Comment by JPRuehmann** [comment]
turpial 3.5.9-dev
libturpial v1.7.0
Problem exists only in Debian.
