### ISSUE TITLE
Show Turpial on double-click in notification area icon

### ISSUE THREAD

**Issue by ashep** [satanas/Turpial#371]
When I hide Turpial with close button and then trying to show its main window gain with double-click on icon in notification area (XFCE), it doesn't appear. Only icon context menu "Show/Hide" works correctly.

**Comment by kopr12** [comment]
Same on Gnome 3.14, would be nice to have this feature working, single or double click.

**Comment by ashep** [comment]
What's the status of this issue? Thanks.

**Comment by nicolas33** [comment]
Works here with simple click. (MATE v1.8.1).
