### ISSUE TITLE
Problemas al actualizar tweets.

### ISSUE THREAD

**Issue by koshrf** [satanas/Turpial#5]
Leyendo tweets, al momento en que se actualiza la lista si hay mensajes nuevos inmediatamente mueve la vista al principio obligando al usuario a tener que volver a bajar para seguir leyendo tweets viejos. El comportamiento correcto debería ser que al momento de llegar un tweet nuevo no se mueva la vista sin permiso de usuario, es fastidioso que uno esté leyendo unos 50-60 tweets nuevos y aleatoriamente vuelva al principio de la lista por que llegó un tweet nuevo.

**Comment by encels** [comment]
Que versión de Turpial tienes? creo que ese problema ya está solventado...

**Comment by koshrf** [comment]
En el "Acerca de" dice Turpial 1.0.

**Comment by koshrf** [comment]
Ya entiendo algo mejor lo que pasa, cuando se clickea un tweet y se usa el teclado para navegar la lista y el tweet seleccionado tiene un color mas obscuro como "seleccionado" al momento de llegar nuevos tweets esta seleción se pierde y se mueve directamente al primer tweet de la lista por lo que al momento de volver a pisar la tecla hacia "abajo" la lista empieza desde el principio. 

La solución real sería que cuando llega un nuevo tweet no se pierda la selección del que se tiene actualmente.

**Comment by satanas** [comment]
This issue will be followed in #251. Closing
