### ISSUE TITLE
Customizable font size

### ISSUE THREAD

**Issue by sdqali** [satanas/Turpial#6]
It would be great if there is an option to select the font/font size.

Is there anyway to do that in the code? Any information about that will also be useful. The font size as it is now is too small, and I find it difficult to read the tweets.

**Comment by nullrend** [comment]
Applies for Turpial 3. Depending on the display used text could be either too big or too small.

**Comment by mwotton** [comment]
any fix for this?

**Comment by satanas** [comment]
There is a way to do it changing the code. Could you post some screenshots to see how big or small the font is? Is there a way to reproduce this behavior?

I would like to test it myself, thus I can adapt the font size without breaking the whole layout

**Comment by mwotton** [comment]
A screenshot wouldn't really show the problem - i have a retina screen.

**Comment by satanas** [comment]
Implemented support for changing font size 8bc0f5d

**Comment by mwotton** [comment]
that's good timing, my new laptop just got here :) Thank you!

**Comment by satanas** [comment]
Your welcome. Please let me know if with this change you can set a better font size for your screen

**Comment by pablopernot** [comment]
That's a great request, change font size. Yes I'm gettin old :)
