### ISSUE TITLE
Problemas diversos con turpial

### ISSUE THREAD

**Issue by petrizzo** [satanas/Turpial#7]
hola gente estoy intentando tener un funcionamiento estable con turpial para poder trabajar mejor con el FAQ sin embargo:
1) No consigo ver todas las features dentro del item preferencias del turpial (no aparece la opción del navegador, por ejemplo). Estoy sobre ubuntu lucid instalado desde 0 y con el turpial cuya descarga se indica en la página respectiva con los repositorios para ubuntu. versión 1.0 del turpial.

2) Con muchísima frecuencia la aplicación se queda colgada:
   a) cuando actualiza un tweet mío que coincide con el momento de la actualización de mi tl. En un 70% de los casos esto hace que el programa se quede colgado (no se cierra, sólo se queda congelado). En el 30% de los casos restantes el programa sigue funcionando pero indica el error en el envío de la información de mi tweet.
   b) cuando realiza la actualización de mi TL, se queda pensando y no lo hace ni indica error, pero si cuelga el programa.
   c) cuando realiza el acortamiento de alguna dirección a través de la opción para ello en el tweet.

3) La demora en cargar el TL en algunos casos es importante (la mediré, lo prometo)

4) Hay demora también en el marcado de twits como favoritos.

Pues nada chicos y chicas lamento dar más problemas que soluciones pero ni una instalación desde cero me ha ayudado a aliviar los problemas. Espero ser más productiva en cuanto tenga una versión má estable para trabajar.

**Comment by satanas** [comment]
Hi @petrizzo, this report is pretty outdated, if any of this issues is still present in Turpial 3 please fill a new issue and we will take it right away
