### ISSUE TITLE
Mientras lo corría en modo depuración: 

### ISSUE THREAD

**Issue by encels** [satanas/Turpial#9]
<blockquote>
<p>Traceback (most recent call last):</p>
<p>  File "/home/encels/turpial/turpial/api/turpialapi.py", line 552, in run</p>
<p>    uri, method))</p>
<p>  File "/home/encels/turpial/turpial/api/oauth_client.py", line 60, in access_resource</p>
<p>    response = urllib2.urlopen(req)</p>
<p>  File "/usr/lib/python2.6/urllib2.py", line 124, in urlopen</p>
<p>    return _opener.open(url, data, timeout)</p>
<p>  File "/usr/lib/python2.6/urllib2.py", line 389, in open</p>
<p>    response = self._open(req, data)</p>
<p>  File "/usr/lib/python2.6/urllib2.py", line 407, in _open</p>
<p>    '_open', req)</p>
<p>  File "/usr/lib/python2.6/urllib2.py", line 367, in _call_chain</p>
<p>    result = func(*args)</p>
<p>  File "/usr/lib/python2.6/urllib2.py", line 1146, in http_open</p>
<p>    return self.do_open(httplib.HTTPConnection, req)</p>
<p>  File "/usr/lib/python2.6/urllib2.py", line 1119, in do_open</p>
<p>    r = h.getresponse()</p>
<p>  File "/usr/lib/python2.6/httplib.py", line 974, in getresponse</p>
<p>    response.begin()</p>
<p>  File "/usr/lib/python2.6/httplib.py", line 391, in begin</p>
<p>    version, status, reason = self._read_status()</p>
<p>  File "/usr/lib/python2.6/httplib.py", line 355, in _read_status</p>
<p>    raise BadStatusLine(line)</p>
<p>BadStatusLine</p>
<p>DEBUG:API:Error for URL: http://api.twitter.com/1/statuses/mentions.json using parameters: ({'count': 100})</p>
<p>details: None</p>
</blockquote>

**Comment by satanas** [comment]
Issue not valid for Turpial 3. Closing
